# PyTorch

- PyTorch is an open-source machine learning library primarily used for deep learning.

- Developed by Facebook's AI Research lab.

- Core features:

    - Tensors – similar to NumPy arrays but with GPU acceleration.

    - Autograd – automatic differentiation for backpropagation.

    - nn Module – build neural networks easily.

    - Optim – pre-built optimizers like SGD, Adam.

    - TorchVision / TorchText – utilities for vision and text datasets.

In [1]:
pip install torch torchvision torchaudio

In [11]:
torch.cuda.is_available()

True

# Tensors – The Core Building Block

- Tensors are multi-dimensional arrays (like NumPy arrays).

- Can run on CPU or GPU (important for training speed).

- Support for mathematical operations, slicing, reshaping.

In [3]:
import torch

# Creating tensors
x = torch.tensor([1, 2, 3])               # 1D tensor
y = torch.zeros((2, 3))                   # 2x3 zero tensor
z = torch.randn((3, 3))                   # 3x3 random tensor

# Basic operations
print(x + 10)
print(y)
print(z)
print(z.mean(), z.std())

# Move to GPU if available
if torch.cuda.is_available():
    z = z.to('cuda')
    print("Tensor on GPU:", z.device)


tensor([11, 12, 13])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.2888, -0.8908,  1.0136],
        [ 1.3821,  0.3857, -0.3654],
        [-0.9882, -0.2891, -1.1232]])
tensor(-0.0652) tensor(0.8931)
Tensor on GPU: cuda:0


# PyTorch Tensor Basics — Quick Revision

- **`torch.tensor(data)`** → Creates a tensor from Python list/array (user-defined data).  
- **`torch.zeros(size)`** → Creates a tensor filled with zeros of given shape.  
- **`torch.ones(size)`** → Creates a tensor filled with ones of given shape.  
- **`torch.rand(size)`** → Creates a tensor with random values ∈ [0, 1).  
- **`torch.randn(size)`** → Creates a tensor with random values from a Normal distribution (mean=0, std=1).  

---

## Device & Conversion Methods  
- **`.to(device)`** → Moves tensor to a specified device (`"cpu"` or `"cuda"`).  
- **`.cpu()`** → Moves tensor to CPU memory.  
- **`.cuda()`** → Moves tensor to GPU memory (if available).  
- **`.numpy()`** → Converts a tensor (on CPU) to a NumPy array (shares memory).  

---

## Shape Manipulation  
- **`.reshape(shape)`** → Returns a tensor with a new shape (data is re-arranged, copy if needed).  
- **`.view(shape)`** → Returns a tensor with a new view of the data (no copy, requires contiguous memory).  
- **`.permute(dims)`** → Changes the order of dimensions (transpose for >2D tensors).  


# Autograd – Automatic Differentiation

- Autograd tracks operations on tensors and computes gradients automatically.

- Essential for training neural networks (backpropagation).

In [7]:
# Create a tensor with gradient tracking
x = torch.tensor([2.0, 3.0], requires_grad=True)

# Some function of x
y = (x ** 2).sum()   # y = x1^2 + x2^2

# Backpropagation
y.backward()

print("x:", x)
print("y:", y)
print("Gradients (dy/dx):", x.grad)


x: tensor([2., 3.], requires_grad=True)
y: tensor(13., grad_fn=<SumBackward0>)
Gradients (dy/dx): tensor([4., 6.])


# PyTorch Autograd

- **`requires_grad=True`** → Tells PyTorch to track operations on this tensor for automatic differentiation (gradients).  
- **`.backward()`** → Computes gradients (backpropagation) for the tensor w.r.t. its computation graph.  
- **`.grad`** → Stores the computed gradient of the tensor after `.backward()` is called.  


# Basic Neural Network with nn.Module

- torch.nn.Module is a base class for all neural network models.

- Layers: nn.Linear, nn.Conv2d, nn.ReLU, nn.Sigmoid, etc.

- Loss functions: nn.MSELoss, nn.CrossEntropyLoss

- Optimizers: torch.optim.SGD, torch.optim.Adam

# PyTorch Neural Network Essentials

- **`torch.nn.Module`** → Base class for all neural network models.  
  - You subclass it and define layers & forward pass in `forward()`.  

---

## Common Layers
- **`nn.Linear(in, out)`** → Fully connected (dense) layer.  
- **`nn.Conv2d(in_channels, out_channels, kernel_size)`** → 2D convolution layer (used in CNNs).  
- **`nn.ReLU()`** → Activation function (keeps positive values, zeroes negatives).  
- **`nn.Sigmoid()`** → Activation function (squashes values to range `[0, 1]`).  

---

## Loss Functions
- **`nn.MSELoss()`** → Mean Squared Error (regression).  
- **`nn.CrossEntropyLoss()`** → Cross-Entropy Loss (classification).  

---

## Optimizers
- **`torch.optim.SGD(model.parameters(), lr=...)`** → Stochastic Gradient Descent optimizer.  
- **`torch.optim.Adam(model.parameters(), lr=...)`** → Adam optimizer (adaptive learning rate).  



In [9]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define Model using nn.Module
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(2, 4)   # Input layer → hidden layer
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(4, 1)   # Hidden layer → output layer
        self.sigmoid = nn.Sigmoid()  # Output activation (binary classification)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.sigmoid(x)
        return x

# Create Model, Loss, Optimizer
model = SimpleNet()
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Sample Data
inputs = torch.tensor([[0.0, 1.0], [1.0, 1.0], [1.0, 0.0]])
targets = torch.tensor([[0.0], [1.0], [1.0]])

# Training Loop (Single Epoch for Demo)
for epoch in range(1):
    optimizer.zero_grad()        # Reset gradients
    outputs = model(inputs)      # Forward pass
    loss = criterion(outputs, targets)  # Compute loss
    loss.backward()              # Backpropagation
    optimizer.step()             # Update weights

    print(f"Predictions: {outputs.detach()}")
    print(f"Loss: {loss.item():.4f}")


Predictions: tensor([[0.2902],
        [0.3150],
        [0.3431]])
Loss: 0.8559
