# TensorFlow Basics

- TensorFlow is an open-source library for **machine learning** and **deep learning**.  
- It uses **tensors** to represent and process data efficiently.

---

## What is a Tensor?

A **tensor** is a multi-dimensional array, similar to NumPy arrays but optimized for GPU/TPU acceleration.  
Tensors can have different ranks (dimensions):

- **Scalar (Rank 0):** A single number.  
  Example:  
  $$
  x = 5
  $$

- **Vector (Rank 1):** A 1-D array.  
  Example:  
  $$
  v = [1, 2, 3]
  $$

- **Matrix (Rank 2):** A 2-D array.  
  Example:  
  $$
  M =
  \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
  \end{bmatrix}
  $$

- **Higher-rank Tensors (Rank 3+):** Stacks of matrices or more complex structures (used for images, sequences, etc.).

---

## Key TensorFlow Terms

- **Graph:**  
  TensorFlow builds a computational graph where nodes represent operations and edges represent tensors flowing between them.

- **Session (TF1.x only):**  
  Used to run graphs in older versions. In TF2.x, **eager execution** is enabled by default, so tensors run immediately like normal Python code.

- **Variable:**  
  Trainable tensors whose values can change during training (weights, biases).

- **Constant:**  
  Fixed tensors that do not change.

- **Placeholder (TF1.x):**  
  Used for feeding external data into a graph. In TF2.x, replaced by normal function arguments.

- **Model:**  
  A neural network is defined using layers (e.g., Dense, Conv2D). Models in TensorFlow are built with either:
  - **Sequential API:** simple stack of layers.
  - **Functional / Subclassing API:** more flexible architectures.

In [1]:
import tensorflow as tf

# Scalar
s = tf.constant(5)

# Vector
v = tf.constant([1, 2, 3])

# Matrix
m = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

print("Scalar:", s)
print("Vector:", v)
print("Matrix:", m)

Scalar: tf.Tensor(5, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
