In [3]:
pip install numpy

## NumPy

* It is known as Numerical Python
* Mostly used for Data analytics and to handle data.

In [2]:
import numpy as np

-----------------------------
## 1. ARRAY CREATION
 -----------------------------
* a = np.array([1, 2, 3])                   ------- # From list
* b = np.zeros((2, 3))                      ------- # All zeros
* c = np.ones((2, 3))                       ------- # All ones
* d = np.full((2, 3), 7)                    ------- # Filled with constant
* e = np.eye(3)                             ------- # Identity matrix
* f = np.empty((2, 2))                      ------- # Uninitialized
* g = np.arange(0, 10, 2)                   ------- # Range with step
* h = np.linspace(0, 1, 5)                  ------- # Equally spaced
* i = np.random.rand(2, 2)                  ------- # Uniform random
* j = np.random.randn(2, 2)                -------  # Normal distribution
* k = np.random.randint(0, 10, size=(2, 2)) ------- # Random integers


In [5]:
lst = [1,2,3]
arr = np.array(lst)
print(arr)
print(type(arr)) # the ndarray means n-dimensional array

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
tup = (1,2,3)
arr = np.array(tup)
print(arr)

[1 2 3]


In [9]:
num = np.arange(1,11)
print(num)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
odd_num = np.arange(1,20,2)
print(odd_num)

[ 1  3  5  7  9 11 13 15 17 19]


In [13]:
even_num = np.arange(2,21,2)
print(even_num)

[ 2  4  6  8 10 12 14 16 18 20]


* multi-dimensional array


In [14]:
lst = [[1,2],[3,4]] # nested lists are rows
matrix = np.array(lst)
print(matrix)

[[1 2]
 [3 4]]


In [18]:
lst = [[1,2],[3,4],[5]] # will through error
matrix = np.array(lst)
print(matrix)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

* array with zero as all elements

In [20]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [24]:
arr = np.zeros([3,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


* array with one as all elements


In [50]:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [51]:
arr = np.ones([3,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


* array with constant element (all elements are same)

In [25]:
arr = np.full(5,1)
print(arr)

[1 1 1 1 1]


In [32]:
arr = np.full((3,3),1)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [33]:
arr = np.full((3,3,3),1)
print(arr)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]




* identity matrix.
* created using eye function and arguemented with order of matrix



In [34]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
identity_matrix = np.eye(10)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [49]:
# numpy.linspace() is a function in the NumPy library used to generate an array
# of evenly spaced numbers over a specified interval.
# This function is particularly useful for creating numerical ranges for various
# applications, including data visualization, simulations, and numerical analysis.
arr = np.linspace(1, 5, 5)
print(arr)

[1. 2. 3. 4. 5.]


* creating array with only diagonal elemnts : `diag`

In [17]:
arr = np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [20]:
arr = np.diag([1,2,3],1)
print(arr)

[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [24]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr)

print(f'diagonal elements : {np.diag(arr)} ')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal elements : [1 5 9] 


* array creation using random
* it gives random numbers (widely used for games like in snake game,when the fruit appears is totally random)

In [54]:
# generate 5 random number between 0 to 1
# rand()
arr = np.random.rand(5)
print(arr)

[0.83178959 0.46975812 0.03078066 0.56138609 0.77576206]


In [55]:
# generate 5 random number between -1.9 to 1.9
# randn
arr = np.random.randn(5)
print(arr)

[-0.34828606 -0.68270751 -1.37173397  0.11404345  0.38704816]


In [56]:
matrix = np.random.rand(3,3)
print(matrix)

[[0.59210479 0.09616932 0.77494666]
 [0.6473119  0.09379464 0.76654255]
 [0.33731634 0.61863007 0.76231619]]


In [57]:
matrix = np.random.randn(3,3)
print(matrix)

[[-0.50132963  1.3212661   1.24543752]
 [ 1.79159586 -2.00135228 -3.21859698]
 [ 1.62527557 -0.6011146  -0.78069507]]


In [60]:
# generate n random integers between a and b
# rand(a,b,n)
arr = np.random.randint(1,50,5)
print(arr)

[22 46 44  6 30]


In [62]:
r1 = np.random.randint(1,10,3)
r2 = np.random.randint(1,10,3)
r3 = np.random.randint(1,10,3)
matrix = np.array((r1,r2,r3))
print(matrix)

[[2 4 9]
 [2 9 6]
 [7 9 3]]


## Array Attributes
This section covers the `ndim`, `shape`, `size`, and `dtype` attributes of an array.

* `ndim` -> it used to check the dimension of array
* `shape` -> it is used to define the matrix order(m * n)
* `size` -> it returns the number of elements in matrix
* `dtype` -> it returns the data type of elements of matrix


In [5]:
# Scalar
a = np.array(42)
print(f"Array 'a' (scalar): {a}, dimension : {a.ndim}")

Array 'a' (scalar): 42, dimension : 0


In [6]:
# 1-dimensional array
b = np.array([1, 2, 3, 4, 5])
print(f"Array 'b' (1D): {b}, dimension : {b.ndim}")

Array 'b' (1D): [1 2 3 4 5], dimension : 1


In [9]:
# 2-dimensional array
c = np.array([[1, 2, 3], [4, 5, 6]])
print(f'''Array 'c' (2D):
{c},
dimension : {c.ndim}''')

Array 'c' (2D): 
[[1 2 3]
 [4 5 6]], 
dimension : 2


In [11]:
# 3-diemnsional array
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f'''Array 'd' (3D):
{d},
dimension : {d.ndim}''')

Array 'd' (3D): 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], 
dimension : 3


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape
array_shape = arr.shape
print(array_shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Total number of elements
total_elements = np.size(arr)
print(f"Total elements: {total_elements}")

# Number of elements along axis 0 (rows)
rows = np.size(arr, axis=0)
print(f"Number of rows: {rows}")

# Number of elements along axis 1 (columns)
cols = np.size(arr, axis=1)
print(f"Number of columns: {cols}")

Total elements: 6
Number of rows: 2
Number of columns: 3


In [16]:
arr1 = np.array([1, 2, 3])
print(f'''arr1 : {arr1} , data_type : {arr1.dtype}''')

# Creating an array with a specified dtype
arr2 = np.array([1.1, 2.2, 3.3], dtype=np.float32)
print(f'''arr2 : {arr2} , data_type : {arr2.dtype}''')

# Changing the dtype of an existing array
arr3 = np.array([1.1, 2.1, 3.1])
new_arr = arr3.astype(int)
print(f'''
old_arr : {arr3} , data_type : {arr3.dtype}
new_arr : {new_arr} , data_type : {new_arr.dtype}''')

arr1 : [1 2 3] , data_type : int64
arr2 : [1.1 2.2 3.3] , data_type : float32

old_arr : [1.1 2.1 3.1] , data_type : float64
new_arr : [1 2 3] , data_type : int64


-----------------------------
## 2. ARRAY MANIPULATION
-----------------------------
* arr = np.array()
* reshaped = arr.reshape(m,n)               ------> # Change shape
* flattened = arr.flatten()                  ------> # Flatten array
* transposed = arr.T                         ------> # Transpose
* raveled = arr.ravel()                      ------> # Flatten (view)
* resized = np.resize(arr, (m, n))           ------> # Resize with * repeat

In [25]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [27]:
matrix_1 = matrix.reshape(3,2)
print(matrix_1)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
matrix_2 = matrix.reshape(6,1)
print(matrix_2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [38]:
print(matrix_1.flatten()) #1D array of all the elements of ndarray

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [37]:
print(matrix_2.ravel()) # only returns the flatten not actually changes the array
print(matrix_2)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [40]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
resized_matrix = np.resize(matrix, (4,2)) # it will repeat in elements in cycle manner(if resizing is done for more than present elemnts)
print(resized_matrix)

[[1 2]
 [3 4]
 [5 6]
 [1 2]]


-----------------------------
## 3. INDEXING & SLICING
-----------------------------
* 0-based indexing
* to locate element in 2d (row,col)
* x = np.array([10, 20, 30, 40, 50])
* element = x[1]                --------> # Single element
* slice_ = x[1:4]               --------> # Slice
* boolean_mask = x[x > 25]      --------> # Boolean indexing
* indexed = x[[0, 2, 4]]        --------> # Fancy indexing


In [54]:
arr = np.array([1,2,3,4,5])
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [59]:
print(f'''2nd element of arr : {arr[1]}
5th element of matrix : {matrix[1,1]}
6th element of 3d matrix : {matrix_3d[0,1,2]}
''')

2nd element of arr : 2  
5th element of matrix : 5  
6th element of 3d matrix : 6 



* fancy indexing : it takes the first form(matrix in case of 3d,row in case of 2d and element is case of 1d) and returns a new array.
* the dimension of this newly formed array will depend on the arguement it took like 3d if matrix is taken

In [61]:
indexed = matrix[[1,0]]
print(indexed)
# it will return the first and second row matrix and display a 2d array as 2 arguemnets are passed

[[4 5 6]
 [1 2 3]]


In [62]:
print(matrix_3d[[1,1]])
#it will return 2nd matrix of matrix_3d two times and it will be 3d array as it takes matrices

[[[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]


In [74]:
boolean_mask = arr[arr < 10]

boolean_mask1 = matrix [matrix > 0]
boolean_mask2 = matrix [matrix[0] > 0]

print(boolean_mask)
print(boolean_mask1)
print(boolean_mask2)

[1 2 3 4 5]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* slicing : for ndarray's we have to first access the 1d array inside present in it by using indexing


In [75]:
arr = np.array([1,2,3,4,5])
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [77]:
arr[1:4]

array([2, 3, 4])

In [79]:
row_1 = matrix[0][0:3]
row_2 = matrix[1][0:3]
row_3 = matrix[2][0:3]
print(f'''
1st row : {row_1}
2nd row : {row_2}
3rd row : {row_3}''')


1st row : [1 2 3]
2nd row : [4 5 6]
3rd row : [7 8 9]


In [81]:
mat_1_row_1 = matrix_3d[0][0][0:3]
print(f'1st row of 1st matrix : {mat_1_row_1}')

1st row of 1st matrix : [1 2 3]


In [84]:
#accessing all the rows of 3D matrix
for i in range(2):
    for j in range(2):
        row = matrix_3d[i][j][0:3]
        print(f'''=> {i+1} matrix -> {j+1} row : {row}''')

=> 1 matrix -> 1 row : [1 2 3]
=> 1 matrix -> 2 row : [4 5 6]
=> 2 matrix -> 1 row : [7 8 9]
=> 2 matrix -> 2 row : [10 11 12]


-----------------------------
## 4. Data types in NumPY
-----------------------------
| Data Type                                | Description                     |
| ---------------------------------------- | ------------------------------- |
| `int8` / `int16` / `int32` / `int64`     | Integer types (signed)          |
| `uint8` / `uint16` / `uint32` / `uint64` | Unsigned integers               |
| `float16` / `float32` / `float64`        | Floating point numbers          |
| `complex64` / `complex128`               | Complex numbers                 |
| `bool_`                                  | Boolean values (`True`/`False`) |
| `object`                                 | Python objects                  |
| `str_` or `U`                            | Unicode strings                 |
| `bytes_` or `S`                          | Byte strings                    |


In [85]:
a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([1.5, 2.5], dtype=np.float64)
c = np.array(["hello", "world"], dtype=np.str_)
d = np.array([True, False], dtype=np.bool_)

print(a.dtype)  # int32
print(b.dtype)  # float64
print(c.dtype)  # <U5 (5-character unicode string)
print(d.dtype)  # bool

int32
float64
<U5
bool


In [86]:
arr = np.array([1.2, 3.4])
int_arr = arr.astype(np.int32)
print(int_arr)       # [1 3]
print(int_arr.dtype) # int32

[1 3]
int32


In [87]:
c = np.array([255, 128, 0], dtype=np.uint8)
print(c, c.dtype)

[255 128   0] uint8


In [88]:
d = np.array([1.5, 2.3, 3.9], dtype=np.float32)
print(d, d.dtype)

e = np.array([3.14159], dtype=np.float64)
print(e, e.dtype)


[1.5 2.3 3.9] float32
[3.14159] float64


In [89]:
f = np.array([1 + 2j, 3 + 4j], dtype=np.complex64)
print(f, f.dtype)

[1.+2.j 3.+4.j] complex64


-----------------------------
## 4. MATHEMATICAL OPERATIONS
-----------------------------
| Operation      | Syntax           | Description                             |
| -------------- | ---------------- | --------------------------------------- |
| Addition       | `a + b`          | Element-wise addition of arrays         |
| Subtraction    | `a - b`          | Element-wise subtraction                |
| Multiplication | `a * b`          | Element-wise multiplication             |
| Division       | `a / b`          | Element-wise division                   |
| Dot Product    | `np.dot(a, b)`   | Computes the dot product of two arrays  |
| Cross Product    | `np.cross(a, b)`   | Computes the cross product of two arrays  |
| Outer Product    | `np.outer(a, b)`   | Computes the outer product of two arrays  |
| Exponential    | `np.exp(a)`      | Exponential (eᵃ) of each element        |
| Square Root    | `np.sqrt(a)`     | Square root of each element             |
| Natural Log    | `np.log(a)`      | Natural logarithm (ln) of each element  |
| Absolute Value | `np.abs(a)`      | Absolute value of each element          |
| Power          | `np.power(a, n)` | Raises each element of `a` to power `n` |**

In [90]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [91]:
add = a + b
print("Addition:", add)

Addition: [5 7 9]


In [93]:
sub = b - a
print("Subtraction:",sub)

Subtraction: [3 3 3]


In [94]:
mul = a * b
print("Multiplication:", mul)

Multiplication: [ 4 10 18]


In [95]:
div = b / a
print("Division:", div)

Division: [4.  2.5 2. ]


In [96]:
dot_prod = np.dot(a, b)
print("Dot Product:", dot_prod)

Dot Product: 32


In [97]:
cross_prod = np.cross(a, b)
print("Cross Product:", cross_prod)

Cross Product: [-3  6 -3]


In [99]:
outer_prod = np.outer(a, b)
print(f'''Outer Product:
{outer_prod}''')

Outer Product: 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [100]:
exp = np.exp(a)
print("Exponential:", exp)

Exponential: [ 2.71828183  7.3890561  20.08553692]


In [101]:
sqrt = np.sqrt(a)
print("Square Root:", sqrt)

Square Root: [1.         1.41421356 1.73205081]


In [102]:
log = np.log(a)
print("Natural Log:", log)

Natural Log: [0.         0.69314718 1.09861229]


In [103]:
neg_array = np.array([-1, -2, 3])
abs_ = np.abs(neg_array)
print("Absolute:", abs_)

Absolute: [1 2 3]


In [104]:
power = np.power(a, 2)
print("Power:", power)

Power: [1 4 9]


-----------------------------
## 5. STATISTICS
-----------------------------
| Operation          | Syntax            | Description                        |
| ------------------ | ----------------- | ---------------------------------- |
| Mean               | `np.mean(data)`   | Average of all elements            |
| Median             | `np.median(data)` | Middle value when sorted           |
| Standard Deviation | `np.std(data)`    | Measure of spread around the mean  |
| Variance           | `np.var(data)`    | Square of standard deviation       |
| Minimum            | `np.min(data)`    | Smallest value in the array        |
| Maximum            | `np.max(data)`    | Largest value in the array         |
| Sum                | `np.sum(data)`    | Sum of all elements                |
| Argmax             | `np.argmax(data)` | Index (flattened) of maximum value |
| Argmin             | `np.argmin(data)` | Index (flattened) of minimum value |



In [105]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [106]:
print(f'''
Mean         = {np.mean(a)}
Median       = {np.median(a)}
Standard Dev = {np.std(a)}
Variance     = {np.var(a)}
Minimum      = {np.min(a)}
Maximum      = {np.max(a)}
Sum          = {np.sum(a)}
Argmax Index = {np.argmax(a)}
Argmin Index = {np.argmin(a)}
''')


Mean         = 5.5
Median       = 5.5
Standard Dev = 2.8722813232690143
Variance     = 8.25
Minimum      = 1
Maximum      = 10
Sum          = 55
Argmax Index = 9
Argmin Index = 0



-----------------------------
## 6. LINEAR ALGEBRA
-----------------------------
| Operation             | Syntax                                    | Description                                  |
| --------------------- | ----------------------------------------- | -------------------------------------------- |
| Determinant           | `np.linalg.det(matrix)`                   | Computes the determinant of a square matrix  |
| Inverse               | `np.linalg.inv(matrix)`                   | Computes the inverse of a square matrix      |
| Eigenvalues           | `np.linalg.eig(matrix)` → returns values  | Finds the eigenvalues of the matrix          |
| Eigenvectors          | `np.linalg.eig(matrix)` → returns vectors | Finds the corresponding eigenvectors         |
| Matrix Multiplication | `np.dot(a, b)` or `a @ b`                 | Performs dot product (matrix multiplication) |
| Solve Ax = b          | `np.linalg.solve(A, b)`                   | Solves a linear system of equations          |


In [115]:
row_1 = [10, 20, 30]
row_2 = [1, 2, 3]
row_3 = [2, 4, 6]
A = np.array([row_1, row_2, row_3])

B = np.array([[7, 8, 10], [10, 11, 12], [13, 14, 15]])

In [120]:
print(f'''
Determinant(A) : {np.linalg.det(A)}
Determinant(B) : {np.linalg.det(B)}
{'---'*10}
Inverse(B) :
{np.linalg.inv(B)}
{'---'*10}
A x B :
{A @ B}
''')


Determinant(A) : 0.0
Determinant(B) : -2.999999999999989
------------------------------
Inverse(B) : 
[[ 1.         -6.66666667  4.66666667]
 [-2.          8.33333333 -5.33333333]
 [ 1.         -2.          1.        ]]
------------------------------
A x B : 
[[660 720 790]
 [ 66  72  79]
 [132 144 158]]



-----------------------------
## 8. Broadcasting
-----------------------------
* Broadcasting in NumPy refers to the ability of NumPy to perform arithmetic operations on arrays of different shapes, without explicitly replicating data.

* It automatically "stretches" or "broadcasts" smaller arrays to match the shape of larger ones during operations.

* Broadcasting Rules
        -> Two arrays are compatible for broadcasting if:

        1. They have the same number of dimensions, or can be prepended with 1s to match.

        2. For each dimension:
            They are equal, or One of them is 1.



In [121]:
# Vector + scalar
a = np.array([1, 2, 3])
b = 10

print(a + b)

[11 12 13]


In [124]:
# 2D + 1D
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)

# b is 1D, shape (3,)
# a is 2D, shape (2, 3)
# b is broadcast across the rows

[[11 22 33]
 [14 25 36]]


In [125]:
# column + row vector
a = np.array([[1],
              [2],
              [3]])  # shape (3,1)

b = np.array([10, 20, 30])  # shape (3,) will become (1,3)

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


-----------------------------
## 8. SET OPERATIONS
-----------------------------
| Operation            | Syntax                 | Description                                    |
| -------------------- | ---------------------- | ---------------------------------------------- |
| Union                | `np.union1d(a, b)`     | All unique elements from both arrays           |
| Intersection         | `np.intersect1d(a, b)` | Common elements between both arrays            |
| Set Difference       | `np.setdiff1d(a, b)`   | Elements in `a` that are not in `b`            |
| Symmetric Difference | `np.setxor1d(a, b)`    | Elements in either `a` or `b`, but not in both |

-> Only applicable for 1d arrays

In [126]:
s1 = np.array([1, 2, 3, 4])
s2 = np.array([3, 4, 5, 6])

In [127]:
union = np.union1d(s1, s2)
intersect = np.intersect1d(s1, s2)
diff = np.setdiff1d(s1, s2)
xor = np.setxor1d(s1, s2)

print(f'''
Set 1             : {s1}
Set 2             : {s2}

Union             : {union}
Intersection      : {intersect}
Set Difference    : {diff}
Symmetric Diff    : {xor}
''')



Set 1             : [1 2 3 4]
Set 2             : [3 4 5 6]

Union             : [1 2 3 4 5 6]
Intersection      : [3 4]
Set Difference    : [1 2]   
Symmetric Diff    : [1 2 5 6]        



-----------------------------
## 9. SORTING & SEARCHING
-----------------------------
| Operation      | Description                                   |
| -------------- | --------------------------------------------- |
| `np.sort()`    | Returns a sorted copy of the array            |
| `np.argsort()` | Returns the indices that would sort the array |
| `np.where()`   | Finds indices matching a condition            |
| `np.nonzero()` | Finds indices where elements are not zero     |

-----------------------------
## 10. COPYING & COMPARISONS
-----------------------------
| Operation           | Description                                                  |
| ------------------- | ------------------------------------------------------------ |
| `np.copy()`         | Creates a **deep copy** of the original array                |
| `orig == [1, 0, 3]` | Performs **element-wise comparison** (returns boolean array) |
| `np.array_equal()`  | Checks if two arrays are **identical in shape and contents** |
